# Generated by Django 5.0.3 on 2024-06-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemq', '0002_unit_station_created_at_station_updated_at_sensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='consuming',
            field=models.BooleanField(default=False),
        ),
    ]
