# Generated by Django 5.0.3 on 2024-07-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatemq', '0003_station_consuming'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['value']},
        ),
        migrations.RenameField(
            model_name='station',
            old_name='consuming',
            new_name='accepted',
        ),
    ]
