# Generated by Django 5.0.3 on 2026-02-04 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemq', '0004_alter_data_options_rename_consuming_station_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('command_key', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='station',
            name='battery_level',
            field=models.FloatField(default=100.0),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('operator', models.CharField(choices=[('>', 'Greater Than'), ('<', 'Less Than'), ('==', 'Equal To')], max_length=2)),
                ('threshold', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='climatemq.actuatoraction')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climatemq.variable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
