# Generated by Django 5.0.3 on 2026-02-11 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemq', '0005_actuatoraction_alter_data_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='station',
        ),
        migrations.RemoveField(
            model_name='station',
            name='battery_level',
        ),
        migrations.AddField(
            model_name='data',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='climatemq.sensor'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='battery_level',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='sensor',
            name='variable',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='climatemq.variable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='climatemq.variable'),
        ),
    ]
