# Generated by Django 5.0.3 on 2026-02-11 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemq', '0006_remove_data_station_remove_station_battery_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='climatemq.sensor'),
        ),
        migrations.AlterField(
            model_name='data',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='climatemq.variable'),
        ),
    ]
