# Generated by Django 5.0.3 on 2026-02-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemq', '0007_alter_data_sensor_alter_data_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='predicted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='predicted_value',
            field=models.FloatField(default=None, null=True),
        ),
    ]
