# Generated by Django 5.0.3 on 2026-02-14 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemq', '0008_sensor_predicted_at_sensor_predicted_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_variance', models.FloatField(default=10.0)),
                ('consecutive_anomalies', models.IntegerField(default=0)),
                ('is_broken', models.BooleanField(default=False)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='climatemq.sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
