# Generated by Django 5.0.3 on 2026-02-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemq', '0009_sensorgoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorgoal',
            name='max_variance',
            field=models.FloatField(default=5.0),
        ),
    ]
