# Generated by Django 5.0.3 on 2026-02-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemq', '0010_alter_sensorgoal_max_variance'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuatoraction',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
